
INSERT IGNORE INTO config VALUES("1", "SKIP_UPLOADING", "false");
INSERT IGNORE INTO config VALUES("2", "DEMO_JWT", "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZW1vIiwiZXhwIjoxOTI1OTgzNTI1LCJpYXQiOjE2MTA2MjM1MjV9.DfgFn1YkN8yuhp5vtZmVZotfJsNXREYIhqnx6KP2OeMESapphWuSDbWe_B_1yrN4ZmBhZs-T1cqJQOvrP-7BKQ");
